# Generated by Django 5.0.7 on 2024-12-14 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], db_index=True, default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='closing_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='file',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purchased_commission_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('Pre-construction', 'Pre-construction'), ('Resale', 'Resale'), ('Commercial', 'Commercial'), ('Line of Credit', 'Line of Credit'), ('Royalty Loan', 'Royalty Loan'), ('Term Loan', 'Term Loan')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['date'], name='deals_deal_date_436460_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['closing_date'], name='deals_deal_closing_e7bb75_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['name'], name='deals_deal_name_332e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company'], name='deals_deal_company_af6a08_idx'),
        ),
    ]
