# Generated by Django 5.0.7 on 2024-09-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='brokerage_name',
            new_name='broker_of_record_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='deal_administrator_name',
            new_name='brokerage_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deal_administrator_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_brokerage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
