# Generated by Django 5.0.7 on 2024-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_brokerage_name_customuser_broker_of_record_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Broker', 'Broker'), ('Deal Administrator', 'Deal Administrator'), ('Other', 'Other')], default='Agent', max_length=100),
        ),
    ]
