# Generated by Django 5.0.7 on 2024-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_deal_administrator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='driver_licenses'),
        ),
    ]
