# Generated by Django 5.0.7 on 2024-12-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_account_number_customuser_institution_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('broker_of_record', models.CharField(max_length=500)),
                ('broker_email', models.CharField(max_length=500)),
                ('deal_administrator_name', models.CharField(max_length=500)),
                ('deal_administrator_email', models.CharField(max_length=500)),
                ('agent_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account_manager', models.CharField(max_length=500)),
                ('stage', models.CharField(choices=[('Running', 'Running'), ('Lost', 'Lost'), ('Prospect', 'Prospect'), ('Work In Progress', 'Work In Progress'), ('Other', 'Other')], default='Prospect', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='broker_of_record_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='broker_of_record_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brokerage_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_brokerage_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deal_administrator_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deal_administrator_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='brokerage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brokerage'),
        ),
    ]
