# Generated by Django 5.0.7 on 2024-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_brokerage_remove_customuser_broker_of_record_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerage',
            options={'verbose_name_plural': 'Brokerages'},
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='company_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='stage',
            field=models.CharField(choices=[('Running', 'Running'), ('Lost', 'Lost'), ('Work In Progress', 'Work In Progress'), ('Prospect', 'Prospect'), ('Other', 'Other')], default='Prospect', max_length=500),
        ),
    ]
