# Generated by Django 5.0.7 on 2024-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_brokerage_options_alter_brokerage_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerage',
            name='account_manager',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='broker_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='broker_of_record',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='deal_administrator_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='deal_administrator_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='province',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brokerage',
            name='stage',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Lost', 'Lost'), ('Work In Progress', 'Work In Progress'), ('Prospect', 'Prospect'), ('Other', 'Other')], default='Prospect', max_length=500, null=True),
        ),
    ]
