# Generated by Django 5.0.7 on 2024-09-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('broker_of_record', models.CharField(max_length=255)),
                ('deal_admin_email', models.EmailField(max_length=254)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('upload_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('purchase_sale_agreement', 'Purchase and Sales Agreement'), ('trade_record_sheet', 'Trade Record Sheet'), ('mls_listing_record', 'MLS Listing Record')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application.brokerage')),
            ],
        ),
    ]
