# Generated by Django 5.0.7 on 2024-09-13 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='brokerage',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('broker_of_record', models.CharField(max_length=255)),
                ('deal_admin_email', models.EmailField(max_length=254)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('upload_id', models.CharField(max_length=50, unique=True)),
                ('purchase_sale_agreement', models.FileField(help_text='Upload Purchase and Sales Agreement (PDF only)', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('mls_listing', models.FileField(help_text='Upload SOLD MLS Listing (PDF only)', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Brokerage',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
