# Generated by Django 5.0.7 on 2024-09-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_application_broker_of_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='new_customer',
        ),
    ]
