# Generated by Django 5.0.7 on 2024-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
