# Generated by Django 5.0.7 on 2024-10-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deal_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
