# Generated by Django 5.0.7 on 2024-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_deal_commission_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='total_commission_amount_received',
            new_name='advance_payout_amount',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='total_commission_amount_requested',
            new_name='discount_fee_amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deal_administrator_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deal_administrator_name',
        ),
        migrations.AddField(
            model_name='application',
            name='advance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='purchase_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='transaction_type',
            field=models.CharField(choices=[('Resale', 'Resale'), ('Commercial', 'Commercial'), ('Pre-construction', 'Pre-construction'), ('Lease', 'Lease')], default='Purchase', max_length=20),
        ),
    ]
