# Generated by Django 5.0.7 on 2024-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_total_commission_amount_received_application_advance_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='transaction_count',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=20),
        ),
    ]
