# Generated by Django 5.0.7 on 2024-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_commission_amount_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Valid ID', 'Valid ID'), ('Purchase and Sale Agreement', 'Purchase and Sale Agreement'), ('SOLD MLS Listing', 'SOLD MLS Listing'), ('Annual Commission Statement', 'Annual Commission Statement'), ('T4A', 'T4A'), ('VOID Cheque', 'VOID Cheque'), ('Direct Deposit Form', 'Direct Deposit Form'), ('Waivers of Conditions', 'Waivers of Conditions'), ('Trade Record Sheet', 'Trade Record Sheet'), ('Deposit Cheque/Receipt', 'Deposit Cheque/Receipt'), ('Exclusive Listing Agreement or Confirmation of Cooperation', 'Exclusive Listing Agreement or Confirmation of Cooperation'), ('Signed Broker Referral with Payment Schedule', 'Signed Broker Referral with Payment Schedule'), ('Receiving/Referral Agreement (if applicable)', 'Receiving/Referral Agreement (if applicable)'), ('Signed Buyer Rep/RECO Info Guide (if direct deal)', 'Signed Buyer Rep/RECO Info Guide (if direct deal)'), ('Signed Trade Record Sheet & Pending Trade Report', 'Signed Trade Record Sheet & Pending Trade Report'), ('Mortgage Pre-approval', 'Mortgage Pre-approval'), ("Developer's Email Confirmation", "Developer's Email Confirmation"), ('Other', 'Other')], max_length=500),
        ),
    ]
