# Generated by Django 5.0.7 on 2024-10-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_changerequest_application_approved_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approved_version',
        ),
    ]
