# Generated by Django 5.0.7 on 2024-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_document_approved_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied')], default='Applied', max_length=10),
        ),
    ]
