# Generated by Django 5.0.7 on 2024-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_changerequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='transaction_type',
            field=models.CharField(choices=[('Resale', 'Resale'), ('Commercial', 'Commercial'), ('Pre-construction', 'Pre-construction'), ('Line of Credit', 'Line of Credit'), ('Lease', 'Lease'), ('Royalty Loan', 'Royalty Loan'), ('Term Loan', 'Term Loan')], default='Purchase', max_length=20),
        ),
    ]
