# Generated by Django 5.0.7 on 2024-09-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='commission_advance_docs')),
                ('document_name', models.CharField(blank=True, max_length=500)),
                ('document_type', models.CharField(choices=[('Purchase and Sale Agreement', 'Purchase and Sale Agreement'), ('Waiver of Conditions', 'Waiver of Conditions'), ('Trade Record Sheet', 'Trade Record Sheet'), ('Deposit Cheque or Receipt', 'Deposit Cheque or Receipt'), ('Copy of Sold MLS Listing', 'Copy of Sold MLS Listing'), ('Other', 'Other')], default='resale', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visible_to_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('amount_per_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='commissionadvancerequest',
            name='copy_of_sold_mls_listing',
        ),
        migrations.RemoveField(
            model_name='commissionadvancerequest',
            name='deposit_cheque_or_receipt',
        ),
        migrations.RemoveField(
            model_name='commissionadvancerequest',
            name='purchase_and_sale_agreement',
        ),
        migrations.RemoveField(
            model_name='commissionadvancerequest',
            name='trade_record_sheet',
        ),
        migrations.RemoveField(
            model_name='commissionadvancerequest',
            name='waivers_of_conditions',
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='funding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='funding_method',
            field=models.CharField(blank=True, choices=[('EFT', 'Electronic Funds Transfer'), ('cheque', 'Cheque')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('contracted', 'Contracted'), ('funded', 'Funded'), ('open', 'Open'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionadvancerequest',
            name='documents',
            field=models.ManyToManyField(blank=True, to='advance.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.ManyToManyField(blank=True, to='advance.documentnote'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advance.commissionadvancerequest')),
                ('invoice_items', models.ManyToManyField(blank=True, to='advance.invoiceitem')),
            ],
        ),
    ]
