# Generated by Django 5.0.7 on 2024-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_email', models.EmailField(blank=True, max_length=254)),
                ('partner_phone', models.CharField(max_length=15)),
                ('partner_address', models.CharField(blank=True, max_length=400)),
                ('website', models.URLField(blank=True)),
                ('partner_logo', models.FileField(blank=True, upload_to='partner_logos/')),
                ('partner_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
